server {
    listen 80;
    server_name bahceifirdevs.com www.bahceifirdevs.com; # ALDIĞIN DOMAIN ADINI YAZ

    # SSL sertifikası alma işlemi için gerekli
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # HTTP'yi HTTPS'e yönlendir (SSL aldıktan sonra burayı açacağız)
    # location / {
    #     return 301 https://$host$request_uri;
    # }
    
    # Geçici olarak (SSL yokken) direk frontend'e yönlendir:
    location / {
        proxy_pass http://frontend:80;
    }
    
    # API İsteklerini Backend'e Yönlendir
    location /api {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}